### ISSUE TITLE
1주차

### ISSUE THREAD

**Issue by MackoLee** [15KauSoftwareKCG/kauSoftware#1]

**Comment by canondoyle** [comment]
안녕

**Comment by IHS49** [comment]
이거 어떻게 전에 말한것들을 보는거지;; 아직 모르겠네요... 정기적인 회의 날짜는 어떻게 잡을까요? 지금 강의수정될게 많아서... 저는 목욜 오후나 금욜이 가능할듯해요.

**Comment by ojh3004** [comment]
저도 일단은 지금 화5시 이후, 목, 금이 비는데 폐강된 과목이 있어서 메꾸면 달라질 수도 있어요.

**Comment by IHS49** [comment]
저는 시간표 확정 났네요

**Comment by IHS49** [comment]
수 = 자유  // 목 = 오후 //  금 = 자유  이렇게 입니다. 다들 수강신청 완료되신후 가능한시간 여기다 올려주세요 이번주에 모임을 가져야겠어요

**Comment by ojh3004** [comment]
일단 현재는 화, 수, 목 - 5시 이후네요. 만약에 컴퓨터비젼도 폐강되면 목요일은 1시부터 가능합니다. (추가) 금요일은 자유입니다.

**Comment by canondoyle** [comment]
저는 월-자유, 화요일 오전, 목 5시 이후네요.

**Comment by MackoLee** [comment]
저는 화,수,금 다섯시 이후입니다

**Comment by cheolgi** [comment]
월 아침 10~11시
화 아침 9~11시, 오후 5~7시
수 오후 전체
목 오후 1~4시
에 안됨

**Comment by IHS49** [comment]
![default](https://cloud.githubusercontent.com/assets/11305751/6571165/36d1eab2-c748-11e4-94e5-0ed51d2b4905.png)

**Comment by IHS49** [comment]
보다시피 시간이 잘 맞지 않네요. 다들 일정 있는시간 즉 불가능한 시간으로 다시상세히 알려주세요. 
위 표는 불가능한 시간을 칠하는 방식으로 작성한겁니다.

**Comment by canondoyle** [comment]
이거 색칠된 시간이 가능한 거죠? 저 수, 금은 1~7 수업이 꽉차있어요

**Comment by canondoyle** [comment]
화요일 3~5시, 수요일 아침 9~ 오후 5시, 목요일 아침 9~10시, 4~6시, 금요일 9~10시랑 1~5시

**Comment by MackoLee** [comment]
수업이 있는 시간이 
월  16시~ 수업 시작 및 농구부
화  10~13시 15~17시 수업
수  13~16시 수업
목  15~ 수업 시작 및 농구부
금  13~17시 수업
저는 아침에 해도 상관이 없습니다

**Comment by IHS49** [comment]
![default](https://cloud.githubusercontent.com/assets/11305751/6573061/9343847e-c75a-11e4-89bd-61c7df607887.png)

**Comment by IHS49** [comment]
모임은 월욜이 좋을듯한데 이번주 회의를 언제해야할지 고민이네요

**Comment by cheolgi** [comment]
우선 월요일 오후로 하고,

내일 저녁 7시 쯤 보기로 하자.

**Comment by IHS49** [comment]
제가 내일 6:30 신촌에서 토스 시험을 봐서 약 7:20분에 끝날듯 합니다. 학교에 도착하면 거의 8시 될듯한데... 괜찮을까요?

**Comment by MackoLee** [comment]
모임 어디서 하나요?

**Comment by cheolgi** [comment]
8시에 하는 거 아니었니?

장소는 내방

2015년 3월 11일 수요일, SangOknotifications@github.com님이 작성한 메시지:

> 모임 어디서 하나요?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/15KauSoftwareKCG/kauSoftware/issues/1#issuecomment-78235814
> .

## 

iPad에서 보낸 메일

**Comment by canondoyle** [comment]
교회 일 때문에 조금 늦을 거 같습니다 8시 까지 가능한 빨리 가겟습니다 죄송합니다

**Comment by IHS49** [comment]
자전거 기어,도난

**Comment by IHS49** [comment]
자전거 기어,도난,navi표시
시각장애인 지팡이
분실 예방 장치
유모차 안전 제어
사진보안

**Comment by canondoyle** [comment]
저 쉅 6시에 끝나는데 어디서 모일까요?

**Comment by cheolgi** [comment]
금요일에 모이기로 하지 않았었나?

나는 7시는 되어야 연구실에 갈것 같은데...

내가 잘못알았다면 미안하다

2015년 3월 12일 목요일, canondoyle<notifications@github.com
<javascript:_e(%7B%7D,'cvml','notifications@github.com');>>님이 작성한 메시지:

> 저 쉅 6시에 끝나는데 어디서 모일까요?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/15KauSoftwareKCG/kauSoftware/issues/1#issuecomment-78434163
> .

## 

iPad에서 보낸 메일

**Comment by cheolgi** [comment]
아... 너희끼리 모이는 건가?

2015년 3월 12일 목요일, Charlie (Cheolgi) Kimcheolgi@gmail.com님이 작성한 메시지:

> 금요일에 모이기로 하지 않았었나?
> 
> 나는 7시는 되어야 연구실에 갈것 같은데...
> 
> 내가 잘못알았다면 미안하다
> 
> 2015년 3월 12일 목요일, canondoylenotifications@github.com님이 작성한 메시지:
> 
> > 저 쉅 6시에 끝나는데 어디서 모일까요?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/15KauSoftwareKCG/kauSoftware/issues/1#issuecomment-78434163
> > .
> 
> ## 
> 
> iPad에서 보낸 메일

## 

iPad에서 보낸 메일

**Comment by IHS49** [comment]
네 저희끼리 모여서 usecase, 시나리오를 작성할 예정입니다 ㅎㅎ
장소는 어제 말씀드린대로 전자 4층으로 오세요

**Comment by cheolgi** [comment]
이슈가 바뀌면 새로운 이슈를 만들고 토론을 하는 것이 좋습니다.

제목도 적절하게 다는 것이 좋을 듯 합니다.

:)

**Comment by MackoLee** [comment]
![image](https://cloud.githubusercontent.com/assets/11310445/6642980/4e2cdaf4-c9ec-11e4-9a1e-2bb7090479d7.jpg)
