### ISSUE TITLE
1학기 진행상황

### ISSUE THREAD

**Issue by IHS49** [15KauSoftwareKCG/kauSoftware#11]
1. 현재 어플리케이션의 기본적인 기능은 구현이 완료 됐지만 예외처리가 부족한 상태 (ex 경로 이탈시 경고 미출력)이며, 이에 대한 알고리즘도 미흡한 상태이다. 2학기 때 어플리케이션의 부족한 점을 잘 보완시켜서 2학기에는 레이저기기에 집중을 하여 제대로 출력시킬수 있도록 구현한다.
2. 레이저가 오후에도 잘 나타나는 제품으로 준비완료 됐으며, 블루투스와 연결을 시켜 핸드폰에서 내놓은 데이터가 잘 수신되는지 테스트는 이루어졌다. 이를 이용하여 2학기때 레이저 기기와 핸드폰의 어플리케이션이 연결될 수 집중적으로 구현할 수 있도록 한다.

**Comment by cheolgi** [comment]
너희 우리 연구실 멀티미터 가지고 있지? 방학중에도 계속 쓸 거니?

2015년 6월 28일 일요일, IHS49notifications@github.com님이 작성한 메시지:

>    1.
> 
>    현재 어플리케이션의 기본적인 기능은 구현이 완료 됐지만 예외처리가 부족한 상태 (ex 경로 이탈시 경고 미출력)이며, 이에
>    대한 알고리즘도 미흡한 상태이다. 2학기 때 어플리케이션의 부족한 점을 잘 보완시켜서 2학기에는 레이저기기에 집중을 하여 제대로
>    출력시킬수 있도록 구현한다.
>    2.
> 
>    레이저가 오후에도 잘 나타나는 제품으로 준비완료 됐으며, 블루투스와 연결을 시켜 핸드폰에서 내놓은 데이터가 잘 수신되는지
>    테스트는 이루어졌다. 이를 이용하여 2학기때 레이저 기기와 핸드폰의 어플리케이션이 연결될 수 집중적으로 구현할 수 있도록 한다.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/15KauSoftwareKCG/kauSoftware/issues/11.

## 

iPad에서 보낸 메일
