### ISSUE TITLE
시나리오

### ISSUE THREAD

**Issue by MackoLee** [15KauSoftwareKCG/kauSoftware#4]

**Comment by SangOk** [comment]
![image](https://cloud.githubusercontent.com/assets/11310445/6638598/08c71e82-c9cb-11e4-9d45-1c9cf5b9f23e.jpg)

**Comment by MackoLee** [comment]
기본실행시나리오
도착지를 입력한다.
도착지의 여러정보들이 리스트로 뜨고
여러정보의 자세한사항들을 보여준다.
자신이 도착하고자 하는 도착지를 누른다.
블루투스로 연결된 기기가 레이저로
길 안내를 시작한다.
그 안내에 따라서 도착지에 도착한다.

**Comment by MackoLee** [comment]
잘못된목적지시나리오 
잘못된 도착지를 입력한다.
도착지의 여러정보들이 리스트로 뜨고
리스트의 자세한 사항을 보여준다
잘못된 도착지를 누른다.
'갈수 없는 지역입니다'라는 창이 띄어지게 되고
경로설정이 종료된다.
