### ISSUE TITLE
대안사항

### ISSUE THREAD

**Issue by MackoLee** [15KauSoftwareKCG/kauSoftware#7]

**Comment by MackoLee** [comment]
레이져가 낮에는 잘보이지 않는것에대한 대안사항을 올려주세요

**Comment by MackoLee** [comment]
저는 진동팔찌를 이용해서 진동 횟수로 방향을 아는것도 괜찮을거같습니다ex) 징~반복=. 오른쪽 징징~ 반복= 왼쪽

**Comment by ojh3004** [comment]
LED로 방향을 나타내는 별도의 장치 장착
